### ISSUE TITLE
Session proposal

### ISSUE THREAD

**Issue by nashjc** [nashjc/Rnavpkg#1]
Original description of proposed session 2016-12-07

**Comment by nashjc** [comment]
Navigating the R packages jungle.
-- A session at UseR2017 on unifying and better navigating the R package collection.

There are now over 9000 packages on CRAN, with many more in Bioconductor, on Github, and
other repositories. How can or should R users navigate this large and unruly collection of packages to find the
tools they need and use them effectively?

There are a number of mechanisms by which users can find appropriate packages for their
needs, but all of them are open to improvement:

  - wrappers like my new optimrx and work I'm doing with Duncan Murdoch on nlsr (an nls()
    successor) allow multiple packages to be accessed via a common, possibly simplified,
    interface. This may not be simple -- optimrx is a successor to optimx which turned out to
    be too complicated in structure.

  - articles/vignettes that compare similar functionality across packages. Claudia
    Beleites and I have started one on Gitlab for PCA and svd tools, but it is at a
    very crude stage. This is a step beyond a Task View in testing small problems to
    verify how packages work, but in some ways more limited in scope by only considering
    certain aspects of some packages.

  - Task Views are a great help when kept up to date, especially if they give some
    guidance to package choice. A potential weakness is that they seem currently to
    rely on one or two volunteers for each. Some form of wiki structure would allow
    bigger teams.

  - CRAN and a superset of CRAN and other repositories are essentially flat lists.
    Structure on the collection is needed, but there are different possibilities for
    organizing the package collection. This would not necessarily involve the CRAN
    team, since structure can be created by an appropriate access wrapper, possibly
    tied into the Task Views. However, there are almost certainly challenges to
    keeping the structure up to date and maintaining balance in any recommendations.

**Comment by aadler** [comment]
Just as papers have abstracts, the DESCRIPTION has its "Description" field. Papers often have keywords as well. If we were to augment the DESCRIPTION file to allow keywords, that may help scripts to organize packages. Right now we have keywords in the documentation files, but I believe those are prescribed and limited in scope. A free-form field may prove valuable.
