### ISSUE TITLE
Keywords in DESCRIPTION?

### ISSUE THREAD

**Issue by aadler** [nashjc/Rnavpkg#2]
Just as papers have abstracts, the DESCRIPTION has its "Description" field. Papers often have keywords as well. If we were to augment the DESCRIPTION file to allow keywords, that may help scripts to organize packages. Right now we have keywords in the documentation files, but I believe those are prescribed and limited in scope. A free-form field may prove valuable.

**Comment by nashjc** [comment]
I added the suggestion to the ideas and people page. I'd prefer to get important ideas in the content rather than comments.

Thanks. JN

**Comment by aadler** [comment]
Sorry, but may I trouble you to spell my name "Avraham", please?

Thanks.

**Comment by nashjc** [comment]
Not sure how that happened since I did copy and paste, but it's corrected now (and thanks for letting me know).

Best, JN

**Comment by aadler** [comment]
Thank you very much. Also, the way you have the wiki set up now, others cannot edit it. What would be the most convenient way for you to receive future suggestions? Would direct e-mail or r-devel be best, or something else? Thank you again!
